# Generated by Django 3.2.4 on 2021-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksamples',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
